version: '3.8'

services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-master
    environment:
      - node.name=elasticsearch-master
      - cluster.name=gameforge-cluster
      - discovery.seed_hosts=elasticsearch-node1,elasticsearch-node2
      - cluster.initial_master_nodes=elasticsearch-master,elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=basic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-master-data:/usr/share/elasticsearch/data
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-master:9200
    ports:
      - "5601:5601"
    networks:
      - elastic-network
    depends_on:
      - elasticsearch-master

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/config:/usr/share/logstash/config:ro
    networks:
      - elastic-network
    depends_on:
      - elasticsearch-master

volumes:
  elasticsearch-master-data:

networks:
  elastic-network:
    driver: bridge
