# Let's Encrypt SSL/TLS Docker Compose Extension
# Add this to your main docker-compose.production-secure.yml

version: '3.8'

services:
  # Certbot for Let's Encrypt certificate management
  certbot:
    image: certbot/certbot:latest
    container_name: gameforge-certbot
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
      - ./ssl/scripts:/scripts
    command: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait; done;"
    networks:
      - gameforge-network
    depends_on:
      - nginx
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL:-admin@yourdomain.com}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Certificate renewal automation
  cert-renewal:
    build:
      context: .
      dockerfile: ssl/Dockerfile.cert-renewal
    container_name: gameforge-cert-renewal
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/backup:/backup
      - ./ssl/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOMAIN=${DOMAIN:-yourdomain.com}
      - EMAIL=${CERTBOT_EMAIL:-admin@yourdomain.com}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
    networks:
      - gameforge-network
    restart: unless-stopped
    depends_on:
      - nginx
      - certbot

networks:
  gameforge-network:
    external: true
