# Windows Docker Compose Override
# This file provides Windows-compatible volume configurations
version: '3.8'

# Override volume definitions to use Windows-compatible paths
volumes:
  gameforge-logs:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\logs
      o: bind

  gameforge-cache:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\cache
      o: bind

  gameforge-assets:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\assets
      o: bind

  gameforge-models:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\models
      o: bind

  monitoring-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\monitoring
      o: bind

  vault-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\vault\data
      o: bind

  vault-logs:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\vault\logs
      o: bind

  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\postgres
      o: bind

  postgres-logs:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\postgres-logs
      o: bind

  redis-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\redis
      o: bind

  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\elasticsearch
      o: bind

  elasticsearch-logs:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\elasticsearch-logs
      o: bind

  logstash-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\logstash
      o: bind

  nginx-logs:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\nginx-logs
      o: bind

  static-files:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\static
      o: bind

  backup-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\backups
      o: bind

  prometheus-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\prometheus
      o: bind

  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\ya754\GameForge\ai-game-production-p\volumes\grafana
      o: bind
