apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gameforge-prod

resources:
- ../../base

patchesStrategicMerge:
- replicas-patch.yaml
- resources-patch.yaml
- security-patch.yaml

configMapGenerator:
- name: app-config
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=info
  - DEBUG=false

secretGenerator:
- name: app-secrets
  literals:
  - DATABASE_URL=${DATABASE_URL}
  - JWT_SECRET=${JWT_SECRET}
  - REDIS_URL=${REDIS_URL}

images:
- name: ghcr.io/sandmanmmm/ai-game-production-p/frontend
  newTag: latest
- name: ghcr.io/sandmanmmm/ai-game-production-p/backend
  newTag: latest
- name: ghcr.io/sandmanmmm/ai-game-production-p/ai-inference
  newTag: latest