version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gameforge-db
    environment:
      POSTGRES_USER: gameforge
      POSTGRES_PASSWORD: gameforge123
      POSTGRES_DB: gameforge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameforge -d gameforge_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  api:
    build: .
    container_name: gameforge-api
    environment:
      DATABASE_URL: postgresql://gameforge:gameforge123@postgres:5432/gameforge_db?schema=public
      PORT: 3001
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
