networks:
  gameforge-network:
    attachable: true
    driver: overlay
services:
  gameforge-app:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4Gi
        reservations:
          cpus: '500'
          memory: 1Gi
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        delay: 10s
        failure_action: pause
        order: stop-first
        parallelism: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
        parallelism: 1
    environment:
    - REDIS_URL=redis://redis:6379
    - GPU_SERVICE_URL=http://gpu-inference:8000
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080/health
      timeout: 10s
    image: gameforge/gameforge-app:latest
    ports:
    - 8080:8080
  gpu-inference:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: 8Gi
        reservations:
          cpus: '1'
          generic_resources:
          - discrete_resource_spec:
              kind: NVIDIA-GPU
              value: 1
          memory: 2Gi
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        delay: 10s
        failure_action: pause
        order: stop-first
        parallelism: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
        parallelism: 1
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUDA_VISIBLE_DEVICES=all
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      timeout: 10s
    image: gameforge/gpu-inference:latest
    ports:
    - 8000:8000
    runtime: nvidia
  nginx:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 512Mi
        reservations:
          cpus: '100'
          memory: 128Mi
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        delay: 10s
        failure_action: pause
        order: stop-first
        parallelism: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
        parallelism: 1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost/health
      timeout: 10s
    image: gameforge/nginx:latest
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '500'
          memory: 1Gi
        reservations:
          cpus: '100'
          memory: 256Mi
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        delay: 10s
        failure_action: pause
        order: stop-first
        parallelism: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
        parallelism: 1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 10s
    image: gameforge/redis:latest
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
version: '3.8'
volumes:
  model_storage: {}
  redis_data: {}
