apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    component: gameforge-ai
  name: redis-deployment
  namespace: gameforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-secret
        image: gameforge/redis:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          httpGet:
            path: /ready
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
