apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-inference
    component: gameforge-ai
  name: gpu-inference-deployment
  namespace: gameforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-inference
  template:
    metadata:
      labels:
        app: gpu-inference
    spec:
      containers:
      - env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: CUDA_VISIBLE_DEVICES
          value: all
        image: gameforge/gpu-inference:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        name: gpu-inference
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
            nvidia.com/gpu: 1
          requests:
            cpu: 1000m
            memory: 2Gi
      nodeSelector:
        accelerator: nvidia-tesla-gpu
