apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gameforge-app
    component: gameforge-ai
  name: gameforge-app-deployment
  namespace: gameforge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameforge-app
  template:
    metadata:
      labels:
        app: gameforge-app
    spec:
      containers:
      - env:
        - name: REDIS_URL
          value: redis://redis-service:6379
        - name: GPU_SERVICE_URL
          value: http://gpu-inference-service:8000
        image: gameforge/gameforge-app:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        name: gameforge-app
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
