apiVersion: v1
kind: Service
metadata:
  labels:
    app: gpu-inference
  name: gpu-inference-service
  namespace: gameforge
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: gpu-inference
  type: ClusterIP
