apiVersion: v1
kind: Service
metadata:
  labels:
    app: gameforge-app
  name: gameforge-app-service
  namespace: gameforge
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: gameforge-app
  type: ClusterIP
