global:
  smtp_smarthost: 'smtp.gameforge.com:587'
  smtp_from: 'audit-alerts@gameforge.com'
  smtp_auth_username: 'audit-system'
  smtp_auth_password: 'secure_smtp_password'

route:
  group_by: ['category', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'audit-team'
  routes:
  - match:
      category: security
    receiver: 'security-team'
    group_wait: 0s
    repeat_interval: 1h
  - match:
      category: compliance
    receiver: 'compliance-team'
    group_wait: 30s
    repeat_interval: 6h
  - match:
      severity: critical
    receiver: 'on-call-team'
    group_wait: 0s
    repeat_interval: 30m

receivers:
- name: 'audit-team'
  email_configs:
  - to: 'audit-team@gameforge.com'
    subject: 'GameForge Audit Alert: {{ .GroupLabels.category }} | {{ .GroupLabels.severity }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Category: {{ .Labels.category }}
      Time: {{ .StartsAt }}
      Runbook: {{ .Annotations.runbook_url }}
      {{ end }}
  webhook_configs:
  - url: 'http://audit-webhook:8080/alerts'
    send_resolved: true

- name: 'security-team'
  email_configs:
  - to: 'security-team@gameforge.com'
    subject: 'SECURITY ALERT: {{ .GroupLabels.category }} | {{ .CommonAnnotations.summary }}'
    body: |
      SECURITY INCIDENT DETECTED

      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Time: {{ .StartsAt }}
      Severity: {{ .Labels.severity }}
      Runbook: {{ .Annotations.runbook_url }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#security-alerts'
    title: 'Security Alert'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
  pagerduty_configs:
  - routing_key: 'security-team-pagerduty-key'
    description: '{{ .CommonAnnotations.summary }}'

- name: 'compliance-team'
  email_configs:
  - to: 'compliance-team@gameforge.com'
    subject: 'Compliance Alert: {{ .CommonAnnotations.summary }}'
    body: |
      COMPLIANCE VIOLATION DETECTED

      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Time: {{ .StartsAt }}
      Severity: {{ .Labels.severity }}
      Framework: {{ .Labels.compliance_framework }}
      Runbook: {{ .Annotations.runbook_url }}
      {{ end }}

- name: 'on-call-team'
  pagerduty_configs:
  - routing_key: 'on-call-pagerduty-key'
    description: 'Critical Audit Alert: {{ .CommonAnnotations.summary }}'
    severity: '{{ .CommonLabels.severity }}'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#on-call'
    title: 'Critical Audit Alert'
    text: '{{ .CommonAnnotations.summary }}'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['category', 'instance']
