global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_by: ['alertname']

receivers:
- name: 'default'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/test/test/test'
    channel: '#alerts'
    title: 'Alert: {{ .GroupLabels.alertname }}'

inhibit_rules: []
