# Trivy Secret Detection Configuration
# Detects hardcoded secrets, API keys, and sensitive information

# Global settings
rules:
  # AWS credentials
  - id: "aws-access-key-id"
    description: "AWS Access Key ID"
    regex: "AKIA[0-9A-Z]{16}"
    severity: "HIGH"
    keywords: ["AKIA"]

  - id: "aws-secret-access-key"  
    description: "AWS Secret Access Key"
    regex: "[A-Za-z0-9/+=]{40}"
    severity: "CRITICAL"
    keywords: ["aws_secret_access_key", "AWSSecretKey"]

  # Azure credentials
  - id: "azure-storage-key"
    description: "Azure Storage Account Key"
    regex: "[A-Za-z0-9+/]{88}=="
    severity: "HIGH"
    keywords: ["DefaultEndpointsProtocol", "AccountKey"]

  - id: "azure-client-secret"
    description: "Azure Client Secret"
    regex: "[A-Za-z0-9_~-]{34}"
    severity: "HIGH"
    keywords: ["client_secret", "AZURE_CLIENT_SECRET"]

  # Database connections
  - id: "postgres-connection"
    description: "PostgreSQL Connection String"
    regex: "postgres://[^\\s]+"
    severity: "MEDIUM"
    keywords: ["postgres://", "postgresql://"]

  - id: "mysql-connection"
    description: "MySQL Connection String" 
    regex: "mysql://[^\\s]+"
    severity: "MEDIUM"
    keywords: ["mysql://"]

  # API Keys
  - id: "openai-api-key"
    description: "OpenAI API Key"
    regex: "sk-[A-Za-z0-9]{48}"
    severity: "HIGH"
    keywords: ["sk-", "openai", "OPENAI_API_KEY"]

  - id: "github-token"
    description: "GitHub Personal Access Token"
    regex: "ghp_[A-Za-z0-9]{36}"
    severity: "HIGH"
    keywords: ["ghp_", "github_token", "GITHUB_TOKEN"]

  - id: "docker-hub-token"
    description: "Docker Hub Access Token"
    regex: "dckr_pat_[A-Za-z0-9_-]{36}"
    severity: "MEDIUM"
    keywords: ["dckr_pat_", "docker_token"]

  # Generic patterns
  - id: "generic-api-key"
    description: "Generic API Key Pattern"
    regex: "api[_-]?key[\"\\s]*[:=][\"\\s]*[A-Za-z0-9]{20,}"
    severity: "MEDIUM"
    keywords: ["api_key", "apikey", "api-key"]

  - id: "jwt-token"
    description: "JWT Token"
    regex: "eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+"
    severity: "MEDIUM"
    keywords: ["eyJ"]

  - id: "private-key"
    description: "Private Key"
    regex: "-----BEGIN [A-Z]+ PRIVATE KEY-----"
    severity: "CRITICAL"
    keywords: ["BEGIN", "PRIVATE KEY"]

# File-specific rules
file-patterns:
  # Configuration files
  - pattern: "**/.env*"
    rules: ["generic-api-key", "aws-access-key-id", "aws-secret-access-key"]
  
  - pattern: "**/config.yaml"
    rules: ["postgres-connection", "mysql-connection", "azure-client-secret"]
  
  - pattern: "**/docker-compose*.yml"
    rules: ["postgres-connection", "mysql-connection"]
  
  # Source code
  - pattern: "**/*.py"
    rules: ["openai-api-key", "generic-api-key", "jwt-token"]
  
  - pattern: "**/*.js"
    rules: ["github-token", "generic-api-key", "jwt-token"]
  
  - pattern: "**/*.ts"
    rules: ["github-token", "generic-api-key", "jwt-token"]

# Allowlist (files/patterns to skip)
allowlist:
  files:
    - "**/test/**"
    - "**/tests/**"
    - "**/*_test.py"
    - "**/*_test.js"
    - "**/example/**"
    - "**/examples/**"
    - "**/docs/**"
    - "**/README.md"
  
  # Test values that are safe to ignore
  values:
    - "your-api-key-here"
    - "replace-with-your-key"
    - "example-key-12345"
    - "test-secret-value"
    - "dummy-token-value"
    - "AKIAIOSFODNN7EXAMPLE"  # AWS example key

# Entropy analysis for unknown secrets
entropy:
  enabled: true
  min_entropy: 4.0
  max_target_length: 120

# Output settings  
output:
  show_source: true
  show_line_numbers: true
  group_by_file: true