# ========================================================================
# Enhanced Prometheus Configuration
# Advanced scraping, recording rules, and alerting
# ========================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'gameforge-production'
    environment: 'production'

# ========================================================================
# Rule Files
# ========================================================================
rule_files:
  - "/etc/prometheus/rules/*.yml"

# ========================================================================
# AlertManager Configuration
# ========================================================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager-enhanced:9093
      timeout: 10s
      api_version: v2

# ========================================================================
# Scrape Configurations
# ========================================================================
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # GameForge Application
  - job_name: 'gameforge-app'
    static_configs:
      - targets: ['gameforge-app:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: gameforge-app:8080

  # GPU Monitoring (NVIDIA)
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['gameforge-app:9400']
    metrics_path: /metrics
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 15s

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # Blackbox Exporter for External Services
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://gameforge-app:8080/health
        - http://grafana-enhanced:3000/api/health
        - http://minio:9000/minio/health/live
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Pushgateway for Batch Jobs
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true

  # Docker Daemon Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 30s

  # Elasticsearch (if available)
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s

  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager-enhanced:9093']
    metrics_path: /metrics
    scrape_interval: 15s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana-enhanced:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: /metrics
    scrape_interval: 30s

# ========================================================================
# Remote Write Configuration (for long-term storage)
# ========================================================================
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     headers:
#       Authorization: "Bearer YOUR_TOKEN"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# ========================================================================
# Storage Configuration
# ========================================================================
storage:
  tsdb:
    retention_time: 30d
    retention_size: 10GB
    wal_compression: true