# ========================================================================
# Prometheus Metrics Configuration for GameForge Production Services
# Custom metrics endpoints and GPU monitoring
# ========================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'gameforge-vastai'
    environment: 'production'

# Load custom alert rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configuration for production services
scrape_configs:
  # ===========================================
  # Infrastructure Monitoring
  # ===========================================
  
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # ===========================================
  # Application Services
  # ===========================================

  # GameForge Main Application
  - job_name: 'gameforge-app'
    static_configs:
      - targets: ['gameforge-app:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gameforge-app-production'

  # GameForge GPU Inference Service
  - job_name: 'gameforge-gpu-inference'
    static_configs:
      - targets: ['gameforge-gpu-inference:8080']
    metrics_path: /metrics
    scrape_interval: 5s  # High frequency for GPU metrics
    scrape_timeout: 3s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gpu-inference-production'

  # GameForge GPU Training Service
  - job_name: 'gameforge-gpu-training'
    static_configs:
      - targets: ['gameforge-gpu-training:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gpu-training-production'

  # GameForge Worker Processes
  - job_name: 'gameforge-workers'
    static_configs:
      - targets: ['gameforge-app:8081']  # Workers metrics endpoint
    metrics_path: /worker_metrics
    scrape_interval: 30s
    params:
      format: ['prometheus']

  # ===========================================
  # Database and Cache Services
  # ===========================================

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s

  # ===========================================
  # Security and Infrastructure
  # ===========================================

  # HashiCorp Vault
  - job_name: 'vault'
    static_configs:
      - targets: ['vault:8200']
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scrape_interval: 30s
    bearer_token: 'vault_prometheus_token'

  # Nginx Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']  # nginx-prometheus-exporter
    metrics_path: /metrics
    scrape_interval: 15s

  # ===========================================
  # Custom Application Metrics
  # ===========================================

  # Custom metrics for model performance
  - job_name: 'model-performance'
    static_configs:
      - targets: ['gameforge-app:8082']  # Custom metrics endpoint
    metrics_path: /model_metrics
    scrape_interval: 10s
    params:
      format: ['prometheus']

  # Security monitoring metrics
  - job_name: 'security-metrics'
    static_configs:
      - targets: ['gameforge-app:8083']  # Security metrics endpoint
    metrics_path: /security_metrics
    scrape_interval: 60s
    params:
      format: ['prometheus']

  # ===========================================
  # GPU-Specific Monitoring
  # ===========================================

  # NVIDIA GPU metrics (via nvidia-ml-py)
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['gpu-exporter:9445']
    metrics_path: /metrics
    scrape_interval: 5s  # High frequency for GPU monitoring
    scrape_timeout: 3s

  # Custom GPU workload metrics
  - job_name: 'gpu-workload-metrics'
    static_configs:
      - targets: ['gameforge-gpu-inference:8084', 'gameforge-gpu-training:8084']
    metrics_path: /gpu_metrics
    scrape_interval: 5s
    params:
      format: ['prometheus']

# Storage configuration for high-retention production data
storage:
  tsdb:
    retention.time: 30d
    retention.size: 100GB
    path: /prometheus/data
    wal-compression: true