autoscaling:
  enabled: true
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 70
image:
  pullPolicy: IfNotPresent
  repository: gameforge-api
  tag: latest
ingress:
  enabled: true
  host: api.gameforge.ai
  tls:
    enabled: true
    secretName: gameforge-tls
postgresql:
  enabled: true
  postgresqlDatabase: gameforge
  postgresqlUsername: gameforge
redis:
  enabled: true
replicaCount: 2
resources:
  limits:
    cpu: 2000m
    memory: 8Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 1000m
    memory: 4Gi
    nvidia.com/gpu: 1
service:
  port: 80
  type: LoadBalancer
