autoscaling:
  enabled: true
  maxReplicas: 10
  minReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
config:
  environment: production
  gpuEnabled: true
  logLevel: INFO
  maxConcurrentRequests: 100
  metricsEnabled: true
  modelCacheSize: 10GB
global:
  imagePullSecrets: []
  imageRegistry: docker.io
  storageClass: fast-ssd
gpu:
  enabled: true
  image:
    repository: gameforge/gpu-inference
    tag: latest
  resources:
    limits:
      cpu: '4'
      memory: 16Gi
      nvidia.com/gpu: '1'
    requests:
      cpu: '2'
      memory: 8Gi
      nvidia.com/gpu: '1'
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: gameforge/app
  tag: latest
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: '100'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  className: nginx
  enabled: true
  hosts:
  - host: gameforge.production.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - gameforge.production.com
    secretName: gameforge-tls
persistence:
  enabled: true
  size: 100Gi
  storageClass: fast-ssd
postgresql:
  auth:
    database: gameforge
    postgresPassword: changeme
  enabled: true
  primary:
    persistence:
      enabled: true
      size: 20Gi
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 20Gi
redis:
  auth:
    enabled: true
    password: changeme
  enabled: true
  master:
    persistence:
      enabled: true
      size: 8Gi
replicaCount: 3
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
secrets:
  apiKey: changeme
  databasePassword: changeme
  encryptionKey: changeme
  jwtSecret: changeme
service:
  port: 80
  targetPort: 8080
  type: ClusterIP
