"""add_user_consent_table

Revision ID: 17d770bf8106
Revises: 28ca5917e1a7
Create Date: 2025-09-14 17:52:38.735283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d770bf8106'
down_revision = '28ca5917e1a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('consent_value', sa.Boolean(), nullable=False),
    sa.Column('purpose_description', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('consent_method', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_classification', sa.String(length=50), nullable=False),
    sa.Column('sensitivity_level', sa.Integer(), nullable=False),
    sa.Column('encryption_required', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('access_pattern', sa.String(length=20), nullable=False),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('archive_after', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.Column('classification_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['user_consent.id'], name=op.f('fk_user_consent_supersedes_id_user_consent')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_consent_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_consent')),
    sa.UniqueConstraint('user_id', 'consent_type', 'is_current', name='uq_user_consent_current')
    )
    op.create_index(op.f('ix_user_consent_archive_after'), 'user_consent', ['archive_after'], unique=False)
    op.create_index(op.f('ix_user_consent_consent_type'), 'user_consent', ['consent_type'], unique=False)
    op.create_index(op.f('ix_user_consent_created_at'), 'user_consent', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_consent_data_classification'), 'user_consent', ['data_classification'], unique=False)
    op.create_index('ix_user_consent_granted_at', 'user_consent', ['granted_at'], unique=False)
    op.create_index(op.f('ix_user_consent_is_current'), 'user_consent', ['is_current'], unique=False)
    op.create_index(op.f('ix_user_consent_owner_id'), 'user_consent', ['owner_id'], unique=False)
    op.create_index(op.f('ix_user_consent_retention_until'), 'user_consent', ['retention_until'], unique=False)
    op.create_index(op.f('ix_user_consent_sensitivity_level'), 'user_consent', ['sensitivity_level'], unique=False)
    op.create_index('ix_user_consent_type_value', 'user_consent', ['consent_type', 'consent_value'], unique=False)
    op.create_index(op.f('ix_user_consent_user_id'), 'user_consent', ['user_id'], unique=False)
    op.create_index('ix_user_consent_user_type_current', 'user_consent', ['user_id', 'consent_type', 'is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_consent_user_type_current', table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_user_id'), table_name='user_consent')
    op.drop_index('ix_user_consent_type_value', table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_sensitivity_level'), table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_retention_until'), table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_owner_id'), table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_is_current'), table_name='user_consent')
    op.drop_index('ix_user_consent_granted_at', table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_data_classification'), table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_created_at'), table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_consent_type'), table_name='user_consent')
    op.drop_index(op.f('ix_user_consent_archive_after'), table_name='user_consent')
    op.drop_table('user_consent')
    # ### end Alembic commands ###
