apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-inference
  name: ai-inference
  namespace: gameforge
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: http
    port: 8001
    targetPort: 8001
  selector:
    app: ai-inference
