apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-inference-models
  namespace: gameforge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
