apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-inference-models
  namespace: gameforge-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
