apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: gameforge
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  selector:
    app: backend
