apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    app.kubernetes.io/component: service
    app.kubernetes.io/name: backend
  name: backend
  namespace: gameforge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value_from_secret: postgres-credentials
        - name: REDIS_URL
          value: redis://redis:6379
        image: gcr.io/distroless/python3-debian11
        name: backend
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
