apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: gameforge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
