apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-grafana-data
  namespace: gameforge-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
