apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: gameforge-prod
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 3000
  selector:
    app: grafana
