apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: gameforge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
