apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-postgres-data
  namespace: gameforge-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
