apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-prometheus-data
  namespace: gameforge-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
