# GameForge Enterprise Secret Rotation Configuration
# Production-ready automation with proper frequencies and policies

# Rotation Schedules (Cron-style for CI/CD integration)
rotation_schedules:
  root_rotation:
    frequency: "0 2 1 */3 *"  # Every 90 days at 2 AM on the 1st of every 3rd month
    description: "Quarterly root token and unseal key rotation"
    requires_manual_approval: true
    critical_secret: true
    notification_channels: ["security-team", "ops-team"]
    
  application_rotation:
    frequency: "0 3 */45 * *"  # Every 45 days at 3 AM
    description: "API keys, model tokens, service credentials"
    requires_manual_approval: false
    critical_secret: false
    notification_channels: ["ops-team"]
    
  tls_rotation:
    frequency: "0 4 */60 * *"  # Every 60 days at 4 AM
    description: "TLS/SSL certificates with Let's Encrypt integration"
    requires_manual_approval: false
    critical_secret: true
    notification_channels: ["security-team", "ops-team"]
    auto_renewal: true
    
  internal_rotation:
    frequency: "0 1 * * *"  # Daily at 1 AM
    description: "Internal service-to-service ephemeral tokens"
    requires_manual_approval: false
    critical_secret: false
    notification_channels: ["ops-team"]
    ttl: "24h"
    
  database_rotation:
    frequency: "0 5 1 */3 *"  # Every 90 days at 5 AM on the 1st of every 3rd month
    description: "Database credentials with rolling restart"
    requires_manual_approval: true
    critical_secret: true
    notification_channels: ["dba-team", "ops-team"]
    requires_restart: true

# Vault Policies for Token TTL Enforcement
vault_policies:
  max_ttl_policies:
    root_tokens: "8760h"      # 365 days maximum
    application_tokens: "1080h"  # 45 days maximum  
    internal_tokens: "24h"       # 24 hours maximum
    database_tokens: "2160h"     # 90 days maximum
    tls_tokens: "1440h"          # 60 days maximum
    
  default_ttl_policies:
    root_tokens: "2160h"      # 90 days default
    application_tokens: "1080h"  # 45 days default
    internal_tokens: "24h"       # 24 hours default
    database_tokens: "2160h"     # 90 days default
    tls_tokens: "1440h"          # 60 days default

# Alert Thresholds
alert_thresholds:
  expiry_warning_days: 7      # Alert when secret expires in 7 days
  critical_warning_days: 3     # Critical alert when secret expires in 3 days
  health_check_failures: 2    # Alert after 2 consecutive health check failures
  rotation_timeout_minutes: 30 # Alert if rotation takes longer than 30 minutes

# Staggering Configuration
stagger_config:
  enable_staggering: true
  stagger_delays:
    root: 0              # No delay for root (highest priority)
    application: 2       # 2 hours after root
    tls: 1              # 1 hour after root
    internal: 0.5       # 30 minutes after root
    database: 4         # 4 hours after root (requires restart)
    
  max_concurrent_rotations: 2  # Maximum 2 secret types rotating simultaneously
  
# Health Check Configuration
health_checks:
  pre_rotation:
    - vault_status
    - secret_accessibility
    - worker_connectivity
    - backup_creation
    
  post_rotation:
    - new_token_validation
    - secret_access_verification
    - worker_authentication_test
    - service_connectivity_check
    
  timeout_seconds: 300
  retry_attempts: 3

# Backup and Recovery
backup_config:
  enable_backups: true
  backup_retention_days: 30
  backup_encryption: true
  backup_locations:
    - "./vault/backups"
    - "s3://gameforge-vault-backups"
  
  recovery_procedures:
    root_failure: "manual_intervention_required"
    application_failure: "automatic_rollback"
    tls_failure: "automatic_rollback"
    internal_failure: "regenerate_tokens"
    database_failure: "manual_intervention_required"

# Notification Configuration
notifications:
  slack:
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      security-team: "#security-alerts"
      ops-team: "#ops-notifications"
      dba-team: "#database-alerts"
      
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    from_address: "vault-rotation@gameforge.com"
    recipients:
      security-team: ["security@gameforge.com"]
      ops-team: ["ops@gameforge.com"]
      dba-team: ["dba@gameforge.com"]
      
  pagerduty:
    integration_key: "${PAGERDUTY_INTEGRATION_KEY}"
    severity_mapping:
      root_failure: "critical"
      database_failure: "critical"
      tls_failure: "high"
      application_failure: "low"
      internal_failure: "low"

# CI/CD Integration
cicd_integration:
  github_actions:
    workflow_file: ".github/workflows/secret-rotation.yml"
    secrets_to_update:
      - "VAULT_ROOT_TOKEN"
      - "VAULT_TOKEN"
      - "HUGGINGFACE_TOKEN"
      - "OPENAI_API_KEY"
      - "DATABASE_PASSWORD"
      
  docker_compose:
    restart_services_after_rotation:
      database: ["gameforge-app", "gameforge-worker"]
      application: ["gameforge-app"]
      tls: ["nginx", "gameforge-app"]
      
  kubernetes:
    secret_update_strategy: "rolling_update"
    restart_deployments:
      database: ["gameforge-backend", "gameforge-worker"]
      application: ["gameforge-backend"]
      tls: ["ingress-nginx"]

# Security Configuration
security_config:
  audit_logging:
    enabled: true
    log_level: "INFO"
    log_destinations:
      - "./logs/audit/vault-rotation.log"
      - "syslog://security-log-server:514"
      
  access_control:
    required_approvers:
      root_rotation: 2        # Requires 2 approvers
      database_rotation: 1    # Requires 1 approver
      tls_rotation: 1        # Requires 1 approver
      
    approval_timeout_hours: 24  # Approval expires after 24 hours
    
  encryption:
    backup_encryption_key: "${BACKUP_ENCRYPTION_KEY}"
    transit_encryption: true
    at_rest_encryption: true

# Monitoring and Metrics
monitoring:
  prometheus_metrics:
    enabled: true
    metrics_port: 9090
    metrics_endpoint: "/metrics"
    
  grafana_dashboards:
    - "vault-secret-rotation-overview"
    - "secret-expiry-tracking"
    - "rotation-health-monitoring"
    
  custom_metrics:
    - name: "vault_secret_rotation_total"
      type: "counter"
      description: "Total number of secret rotations"
      
    - name: "vault_secret_expiry_days"
      type: "gauge"
      description: "Days until secret expiry"
      
    - name: "vault_rotation_duration_seconds"
      type: "histogram"
      description: "Time taken for secret rotation"

# Environment-Specific Overrides
environments:
  development:
    rotation_schedules:
      root_rotation:
        frequency: "0 2 * * 0"  # Weekly on Sunday for testing
      application_rotation:
        frequency: "0 3 * * *"  # Daily for testing
        
  staging:
    rotation_schedules:
      root_rotation:
        frequency: "0 2 */30 * *"  # Every 30 days
      application_rotation:
        frequency: "0 3 */15 * *"  # Every 15 days
        
  production:
    # Use default schedules defined above
    strict_approval_required: true
    enable_canary_deployments: true
