# Prometheus Configuration for GameForge AI Platform on Vast.ai RTX 4090
# Comprehensive monitoring for GPU-accelerated AI workloads

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'gameforge-vastai-rtx4090'
    environment: 'production'

# =============================================================================
# Rule Files for Alerting
# =============================================================================
rule_files:
  - "alert_rules.yml"

# =============================================================================
# Alertmanager Configuration
# =============================================================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

# =============================================================================
# Scrape Configurations
# =============================================================================
scrape_configs:
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # TorchServe Metrics (RTX 4090 Optimized)
  - job_name: 'torchserve'
    static_configs:
      - targets: ['torchserve:8082']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rtx4090-torchserve'
      - target_label: gpu_model
        replacement: 'rtx4090'
      - target_label: service
        replacement: 'torchserve'

  # GPU Monitoring (DCGM Exporter)
  - job_name: 'gpu-monitor'
    static_configs:
      - targets: ['gpu-monitor:9400']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rtx4090-gpu'
      - target_label: gpu_model
        replacement: 'rtx4090'
      - target_label: vram_size
        replacement: '24gb'

  # Ray Cluster Metrics
  - job_name: 'ray-head'
    static_configs:
      - targets: ['ray-head:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'
    relabel_configs:
      - target_label: service
        replacement: 'ray-head'
      - target_label: gpu_model
        replacement: 'rtx4090'

  # MLflow Metrics
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    scrape_interval: 60s
    metrics_path: '/metrics'
    relabel_configs:
      - target_label: service
        replacement: 'mlflow'

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Container Metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# =============================================================================
# Remote Write Configuration (Optional for long-term storage)
# =============================================================================
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     headers:
#       Authorization: "Bearer YOUR_TOKEN"

# =============================================================================
# Storage Configuration
# =============================================================================
storage:
  tsdb:
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true
