apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gameforge-prometheus-pdb
  namespace: gameforge-monitoring
  labels:
    app.kubernetes.io/name: gameforge-prometheus
    app.kubernetes.io/component: monitoring
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: gameforge-prometheus
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
  namespace: gameforge-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
