apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# AWS EKS Cloud Overlay
# Extends production overlay with AWS-specific configurations

namespace: gameforge-monitoring

resources:
- ../../overlays/production
- aws-loadbalancer-config.yaml
- aws-storage-classes.yaml

components:
- ../../components/node-affinity
- ../../components/high-availability

patchesStrategicMerge:
- aws-service-patches.yaml
- aws-deployment-patches.yaml

images:
- name: gameforge
  newName: 123456789012.dkr.ecr.us-west-2.amazonaws.com/gameforge
  newTag: latest
- name: prometheus/prometheus
  newName: 123456789012.dkr.ecr.us-west-2.amazonaws.com/prometheus
  newTag: v2.45.0
- name: grafana/grafana
  newName: 123456789012.dkr.ecr.us-west-2.amazonaws.com/grafana
  newTag: 10.0.0

configMapGenerator:
- name: aws-config-prod
  literals:
  - AWS_REGION=us-west-2
  - CLOUD_PROVIDER=aws
  - CLUSTER_NAME=gameforge-production
  - LOAD_BALANCER_TYPE=nlb

secretGenerator:
- name: aws-secrets-prod
  literals:
  - AWS_ACCESS_KEY_ID=placeholder
  - AWS_SECRET_ACCESS_KEY=placeholder
  type: Opaque

replicas:
- name: gameforge-prometheus-prod
  count: 2  # Restore HA with proper storage
- name: gameforge-grafana-prod
  count: 2
