version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: gameforge-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
      - '--web.listen-address=0.0.0.0:9093'
      - '--cluster.listen-address=0.0.0.0:9094'
      - '--log.level=info'
    volumes:
      - alertmanager_data:/alertmanager
      - ./monitoring/alerting/configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./monitoring/alerting/templates:/etc/alertmanager/templates:ro
    networks:
      - gameforge-monitoring
    environment:
      - TZ=UTC
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9093"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  webhook-handler:
    build:
      context: ./monitoring/alerting/webhooks
      dockerfile: Dockerfile
    container_name: gameforge-webhook-handler
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - WEBHOOK_PORT=8080
      - LOG_LEVEL=info
      - GAMEFORGE_API_URL=http://gameforge-api:8000
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
    volumes:
      - ./monitoring/alerting/webhooks/config.yaml:/app/config.yaml:ro
      - webhook_logs:/app/logs
    networks:
      - gameforge-monitoring
    depends_on:
      - alertmanager

  alert-scheduler:
    image: python:3.11-slim
    container_name: gameforge-alert-scheduler
    restart: unless-stopped
    working_dir: /app
    command: python alert_scheduler.py
    volumes:
      - ./monitoring/alerting/scripts:/app:ro
      - scheduler_data:/app/data
    environment:
      - ALERTMANAGER_URL=http://alertmanager:9093
      - PROMETHEUS_URL=http://prometheus:9090
      - SCHEDULER_INTERVAL=300
    networks:
      - gameforge-monitoring
    depends_on:
      - alertmanager

networks:
  gameforge-monitoring:
    external: true
    name: gameforge-network

volumes:
  alertmanager_data:
    driver: local
  webhook_logs:
    driver: local
  scheduler_data:
    driver: local
