# GameForge AI System - Lightweight Production Test
# This version uses CPU-only to avoid bus errors during testing
version: '3.8'

services:
  # Redis for queue management and caching
  redis:
    image: redis:7.2-alpine
    container_name: gameforge-redis-test
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gameforge-network

  # GameForge AI Service (CPU-only for testing)
  gameforge-ai:
    build:
      context: .
      dockerfile: gameforge-ai-lightweight.Dockerfile
    container_name: gameforge-ai-test
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GAMEFORGE_ENV=production
      - LOG_LEVEL=info
      - PYTORCH_DEVICE=cpu
    volumes:
      - ./generated_assets:/app/generated_assets
      - ./logs:/app/logs
      - ./config:/app/config:ro
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - gameforge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Load Balancer (nginx)
  nginx:
    image: nginx:1.25-alpine
    container_name: gameforge-nginx-test
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.production.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/static:ro
    depends_on:
      - gameforge-ai
    networks:
      - gameforge-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  gameforge-network:
    driver: bridge
