# HashiCorp Vault Secrets Management Docker Compose
version: '3.8'

services:
  # Vault primary node
  vault-primary:
    image: hashicorp/vault:1.15.2
    container_name: gameforge-vault-primary
    hostname: vault-primary
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://vault-primary:8200"
      VAULT_CLUSTER_ADDR: "http://vault-primary:8201"
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {
            "consul": {
              "address": "consul:8500",
              "path": "vault/",
              "ha_enabled": "true",
              "lock_wait_time": "25s",
              "consistency_mode": "strong"
            }
          },
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "cluster_address": "0.0.0.0:8201",
                "tls_disable": 1
              }
            }
          ],
          "cluster_addr": "http://vault-primary:8201",
          "api_addr": "http://vault-primary:8200",
          "disable_mlock": true,
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true,
          "log_level": "INFO",
          "plugin_directory": "/vault/plugins"
        }
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./secrets/vault/data:/vault/data
      - ./secrets/vault/logs:/vault/logs
      - ./secrets/vault/config:/vault/config
      - ./secrets/vault/policies:/vault/policies
      - ./secrets/vault/scripts:/vault/scripts
    cap_add:
      - IPC_LOCK
    networks:
      - gameforge-network
      - vault-network
    depends_on:
      - consul
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["vault", "server", "-config=/vault/config/vault.hcl"]

  # Vault secondary node for HA
  vault-secondary:
    image: hashicorp/vault:1.15.2
    container_name: gameforge-vault-secondary
    hostname: vault-secondary
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://vault-secondary:8200"
      VAULT_CLUSTER_ADDR: "http://vault-secondary:8201"
      VAULT_LOCAL_CONFIG: |
        {
          "storage": {
            "consul": {
              "address": "consul:8500",
              "path": "vault/",
              "ha_enabled": "true",
              "lock_wait_time": "25s",
              "consistency_mode": "strong"
            }
          },
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "cluster_address": "0.0.0.0:8201",
                "tls_disable": 1
              }
            }
          ],
          "cluster_addr": "http://vault-secondary:8201",
          "api_addr": "http://vault-secondary:8200",
          "disable_mlock": true,
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": false,
          "log_level": "INFO"
        }
    ports:
      - "8210:8200"
      - "8211:8201"
    volumes:
      - ./secrets/vault/data:/vault/data
      - ./secrets/vault/logs:/vault/logs
      - ./secrets/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    networks:
      - gameforge-network
      - vault-network
    depends_on:
      - consul
      - vault-primary
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    command: ["vault", "server", "-config=/vault/config/vault.hcl"]

  # Consul for Vault storage backend
  consul:
    image: hashicorp/consul:1.16.1
    container_name: gameforge-consul
    hostname: consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    ports:
      - "8500:8500"
      - "8600:8600"
    volumes:
      - consul_data:/consul/data
      - ./secrets/vault/config/consul.json:/consul/config/consul.json
    networks:
      - vault-network
    restart: unless-stopped
    command: ["consul", "agent", "-config-file=/consul/config/consul.json"]

  # Vault agent for secret injection
  vault-agent:
    image: hashicorp/vault:1.15.2
    container_name: gameforge-vault-agent
    environment:
      VAULT_ADDR: "http://vault-primary:8200"
    volumes:
      - ./secrets/vault/config/agent.hcl:/vault/config/agent.hcl
      - ./secrets/vault/data:/vault/data
      - ./secrets/docker/swarm:/vault/secrets
      - vault_agent_cache:/vault/cache
    networks:
      - gameforge-network
      - vault-network
    depends_on:
      - vault-primary
    restart: unless-stopped
    command: ["vault", "agent", "-config=/vault/config/agent.hcl"]

  # Secret rotation service
  vault-rotator:
    build:
      context: .
      dockerfile: secrets/Dockerfile.vault-rotator
    container_name: gameforge-vault-rotator
    environment:
      VAULT_ADDR: "http://vault-primary:8200"
      VAULT_TOKEN: ${VAULT_ROTATION_TOKEN}
      ROTATION_INTERVAL: "24h"
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    volumes:
      - ./secrets/rotation:/rotation
      - ./secrets/vault/scripts:/scripts
    networks:
      - gameforge-network
      - vault-network
    depends_on:
      - vault-primary
    restart: unless-stopped

volumes:
  consul_data:
    driver: local
  vault_agent_cache:
    driver: local

networks:
  vault-network:
    driver: bridge
    internal: true
  gameforge-network:
    external: true
