global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'gameforge-alerts@company.com'
  smtp_auth_username: 'gameforge-alerts@company.com'
  smtp_auth_password: 'your_smtp_password'
  smtp_require_tls: true

  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

  # GameForge specific settings
  http_config:
    proxy_url: 'http://proxy.company.com:8080'

  # Custom webhook settings
  webhook_url: 'http://gameforge-webhook-handler:8080/alerts'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'gameforge-default'

  routes:
  # Critical alerts - immediate escalation
  - match:
      severity: critical
    receiver: 'gameforge-critical'
    group_wait: 0s
    group_interval: 5m
    repeat_interval: 15m
    routes:
    - match:
        alertname: GPUCriticalTemperature
      receiver: 'gameforge-gpu-critical'
    - match:
        alertname: GameForgeServiceDown
      receiver: 'gameforge-service-critical'
    - match:
        alertname: DatabaseDown
      receiver: 'gameforge-database-critical'

  # GPU specific alerts
  - match:
      component: gpu
    receiver: 'gameforge-gpu-team'
    group_by: ['alertname', 'gpu', 'instance']

  # Business critical alerts
  - match:
      category: business
    receiver: 'gameforge-business-team'
    group_by: ['alertname', 'service']

  # Security alerts
  - match:
      category: security
    receiver: 'gameforge-security-team'
    group_wait: 0s
    repeat_interval: 5m

  # AI/ML service alerts
  - match:
      service: gameforge-ai
    receiver: 'gameforge-ai-team'

  # Infrastructure alerts
  - match:
      category: infrastructure
    receiver: 'gameforge-infrastructure-team'

  # Development environment alerts (non-critical)
  - match:
      environment: development
    receiver: 'gameforge-dev-team'
    repeat_interval: 4h

# Inhibition rules
inhibit_rules:
# Inhibit any warning-level alerts if the same alert is already critical
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']

# Inhibit GPU utilization warnings if GPU is down
- source_match:
    alertname: 'GPUDown'
  target_match:
    component: 'gpu'
  equal: ['instance']

# Inhibit service alerts if the entire node is down
- source_match:
    alertname: 'NodeDown'
  target_match:
    component: 'service'
  equal: ['instance']

# Receivers configuration
receivers:
# Default receiver
- name: 'gameforge-default'
  email_configs:
  - to: 'gameforge-ops@company.com'
    subject: '[GameForge] {{ .GroupLabels.alertname }} - {{ .Status | toUpper }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      {{ end }}

# Critical alerts - multiple channels
- name: 'gameforge-critical'
  email_configs:
  - to: 'gameforge-critical@company.com'
    subject: '🚨 [CRITICAL] GameForge Alert: {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL ALERT DETECTED

      {{ range .Alerts }}
      🚨 Alert: {{ .Annotations.summary }}
      📝 Description: {{ .Annotations.description }}
      🏷️  Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
      🕐 Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ if .EndsAt }}🕐 Ended: {{ .EndsAt.Format "2006-01-02 15:04:05" }}{{ end }}
      {{ end }}

  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/CRITICAL/WEBHOOK'
    channel: '#gameforge-critical'
    title: '🚨 Critical GameForge Alert'
    text: |
      {{ range .Alerts }}
      *{{ .Annotations.summary }}*
      {{ .Annotations.description }}
      {{ end }}
    send_resolved: true

  pagerduty_configs:
  - routing_key: 'your_pagerduty_integration_key'
    description: '{{ .GroupLabels.alertname }} - {{ .Status | toUpper }}'
    details:
      alert_count: '{{ len .Alerts }}'
      alerts: |
        {{ range .Alerts }}
        - {{ .Annotations.summary }}
        {{ end }}

# GPU team alerts
- name: 'gameforge-gpu-team'
  email_configs:
  - to: 'gameforge-gpu-team@company.com'
    subject: '[GameForge GPU] {{ .GroupLabels.alertname }}'
    body: |
      GPU Alert Detected

      {{ range .Alerts }}
      GPU: {{ .Labels.gpu }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Current Value: {{ .Annotations.value }}
      {{ end }}

  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/GPU/WEBHOOK'
    channel: '#gameforge-gpu'
    title: '🖥️ GPU Alert'
    text: |
      {{ range .Alerts }}
      *GPU {{ .Labels.gpu }}*: {{ .Annotations.summary }}
      Value: {{ .Annotations.value }}
      {{ end }}

# GPU critical alerts
- name: 'gameforge-gpu-critical'
  email_configs:
  - to: 'gameforge-gpu-team@company.com,gameforge-critical@company.com'
    subject: '🔥 [CRITICAL GPU] {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL GPU ALERT

      {{ range .Alerts }}
      🔥 GPU {{ .Labels.gpu }} CRITICAL ISSUE
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Temperature: {{ .Annotations.value }}°C

      IMMEDIATE ACTION REQUIRED
      {{ end }}

  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/CRITICAL/WEBHOOK'
    channel: '#gameforge-critical'
    title: '🔥 CRITICAL GPU ALERT'
    text: |
      {{ range .Alerts }}
      *CRITICAL*: GPU {{ .Labels.gpu }} at {{ .Annotations.value }}°C
      {{ .Annotations.description }}
      {{ end }}

  webhook_configs:
  - url: 'http://gameforge-webhook-handler:8080/gpu-critical'
    send_resolved: true

# Business team alerts
- name: 'gameforge-business-team'
  email_configs:
  - to: 'gameforge-business@company.com'
    subject: '[GameForge Business] {{ .GroupLabels.alertname }}'
    body: |
      Business Metric Alert

      {{ range .Alerts }}
      Metric: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Current Value: {{ .Annotations.value }}
      {{ end }}

# Security team alerts
- name: 'gameforge-security-team'
  email_configs:
  - to: 'gameforge-security@company.com'
    subject: '🔒 [GameForge Security] {{ .GroupLabels.alertname }}'
    body: |
      Security Alert Detected

      {{ range .Alerts }}
      🔒 Security Issue: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Source: {{ .Labels.instance }}
      {{ end }}

  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SECURITY/WEBHOOK'
    channel: '#gameforge-security'
    title: '🔒 Security Alert'
    text: |
      {{ range .Alerts }}
      *Security Issue*: {{ .Annotations.summary }}
      {{ .Annotations.description }}
      {{ end }}

# AI team alerts
- name: 'gameforge-ai-team'
  email_configs:
  - to: 'gameforge-ai-team@company.com'
    subject: '[GameForge AI] {{ .GroupLabels.alertname }}'
    body: |
      AI Service Alert

      {{ range .Alerts }}
      AI Service: {{ .Labels.service }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}

# Infrastructure team alerts
- name: 'gameforge-infrastructure-team'
  email_configs:
  - to: 'gameforge-infra@company.com'
    subject: '[GameForge Infra] {{ .GroupLabels.alertname }}'
    body: |
      Infrastructure Alert

      {{ range .Alerts }}
      Component: {{ .Labels.component }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}

# Service critical alerts
- name: 'gameforge-service-critical'
  email_configs:
  - to: 'gameforge-critical@company.com'
    subject: '🚨 [SERVICE DOWN] {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL SERVICE FAILURE

      {{ range .Alerts }}
      🚨 Service: {{ .Labels.service }}
      Status: {{ .Annotations.summary }}
      Impact: {{ .Annotations.description }}
      {{ end }}

  pagerduty_configs:
  - routing_key: 'your_service_pagerduty_key'
    description: 'GameForge Service Down: {{ .GroupLabels.alertname }}'

# Database critical alerts  
- name: 'gameforge-database-critical'
  email_configs:
  - to: 'gameforge-dba@company.com,gameforge-critical@company.com'
    subject: '💾 [DATABASE CRITICAL] {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL DATABASE ISSUE

      {{ range .Alerts }}
      💾 Database: {{ .Labels.database }}
      Issue: {{ .Annotations.summary }}
      Details: {{ .Annotations.description }}
      {{ end }}

# Development team alerts (lower priority)
- name: 'gameforge-dev-team'
  email_configs:
  - to: 'gameforge-dev@company.com'
    subject: '[GameForge Dev] {{ .GroupLabels.alertname }}'
    body: |
      Development Environment Alert

      {{ range .Alerts }}
      Environment: {{ .Labels.environment }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}
