global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'gameforge-gpu'
    datacenter: 'primary'

rule_files:
  - "gpu-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nvidia-gpu-exporter'
    static_configs:
      - targets: ['nvidia-gpu-exporter:9835']
    scrape_interval: 10s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'gameforge-api'
    static_configs:
      - targets: ['gameforge-api:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'gameforge-ai-service'
    static_configs:
      - targets: ['gameforge-ai:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'docker-metrics'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 30s

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
