apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus-uid
    jsonData:
      httpMethod: POST
      keepCookies: []
      timeInterval: 15s
      tlsSkipVerify: false
    secureJsonData: {}

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logstash-*"
    basicAuth: true
    basicAuthUser: elastic
    editable: true
    uid: elasticsearch-uid
    jsonData:
      esVersion: "8.9.0"
      includeFrozen: false
      interval: Daily
      logLevelField: level
      logMessageField: message
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
    secureJsonData:
      basicAuthPassword: ${ELASTIC_PASSWORD}
