apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gameforge-storage
  namespace: gameforge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
