apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gameforge-secret-rotation-production-simple
  annotations:
    config.kubernetes.io/local-config: "true"

# Base configuration
resources:
- ../../base

# Production-specific labels
labels:
- pairs:
    environment: production
    tier: production
  
# Production annotations
commonAnnotations:
  deployment.kubernetes.io/environment: "production"

# Name suffix for production
nameSuffix: -prod

# Production image tags
images:
- name: gameforge/secret-rotation
  newTag: v1.0.0-production
- name: gameforge/security-monitor
  newTag: v1.0.0-production
- name: prom/prometheus
  newTag: v2.47.0
- name: grafana/grafana
  newTag: 10.1.0

# Production replica counts
replicas:
- name: gameforge-prometheus
  count: 2
- name: gameforge-grafana
  count: 1

# Production configuration generators
configMapGenerator:
- name: production-config
  literals:
  - environment=production
  - log_level=INFO
  - vault_max_retries=5
  options:
    disableNameSuffixHash: false
