apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameforge-prometheus
  namespace: gameforge-monitoring
spec:
  replicas: 1  # Single instance to avoid storage conflicts (TODO: Convert to StatefulSet for HA)
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.enable-lifecycle'
        - '--web.route-prefix=/'
        - '--storage.tsdb.retention.time=90d'  # Extended retention for production
        - '--storage.tsdb.retention.size=50GB'
        - '--web.enable-admin-api'
        - '--web.external-url=https://prometheus.gameforge.com'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameforge-grafana
  namespace: gameforge-monitoring
spec:
  template:
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_SERVER_ROOT_URL
          value: "https://grafana.gameforge.com"
        - name: GF_SECURITY_COOKIE_SECURE
          value: "true"
        - name: GF_SECURITY_STRICT_TRANSPORT_SECURITY
          value: "true"
        - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
          value: "Viewer"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_ALERTING_ENABLED
          value: "true"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gameforge-secret-rotation-internal
  namespace: gameforge-security
spec:
  schedule: "0 1 * * *"  # Production schedule
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: secret-rotation
            env:
            - name: ENVIRONMENT
              value: "production"
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_MONITORING
              value: "true"
            - name: ENABLE_ALERTS
              value: "true"
            resources:
              requests:
                memory: "512Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gameforge-security-monitor
  namespace: gameforge-monitoring
spec:
  template:
    spec:
      containers:
      - name: node-exporter
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: security-monitor
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENABLE_SECURITY_CHECKS
          value: "true"
        - name: ALERT_ON_FAILURES
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
