apiVersion: 1

datasources:
  # Existing Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: "POST"

  # Jaeger datasource for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    basicAuth: false
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      # Jaeger specific settings
      tracesToLogs:
        datasourceUid: "loki"
        tags: ["job", "instance", "pod", "namespace"]
        mappedTags:
          - name: "service.name"
            value: "service"
        mapTagNamesEnabled: true
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: "prometheus"
        tags:
          - key: "service.name"
            value: "service"
          - key: "job"
        queries:
          - name: "Sample query"
            query: "sum(rate(http_requests_total[$__rate_interval]))"
      serviceMap:
        datasourceUid: "prometheus"
      nodeGraph:
        enabled: true

  # Elasticsearch datasource for logs correlation
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    basicAuth: true
    basicAuthUser: "elastic"
    secureJsonData:
      basicAuthPassword: "${ELASTIC_PASSWORD}"
    jsonData:
      index: "gameforge-logs-*"
      timeField: "@timestamp"
      esVersion: "8.9.0"
      logMessageField: "message"
      logLevelField: "level"
      # Correlation with traces
      includeFrozen: false
      maxConcurrentShardRequests: 5

  # OpenTelemetry Collector metrics
  - name: OTel Collector
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    basicAuth: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: "POST"
