apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: gameforge-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: config
data:
  # Default datasource configuration
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://gameforge-prometheus-prod:9090
      isDefault: true
      editable: false
      jsonData:
        httpMethod: GET
        keepCookies: []
        manageAlerts: true
        prometheusType: Prometheus
        prometheusVersion: 2.47.0
        cacheLevel: 'Low'
        disableRecordingRules: false
        incrementalQueryOverlapWindow: 10m
        scrapeInterval: '30s'
        queryTimeout: '60s'
        defaultRegion: 'default'

  # Dashboard provider configuration
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards

  # Basic Grafana configuration
  grafana.ini: |
    [analytics]
    check_for_updates = false
    reporting_enabled = false

    [log]
    mode = console
    level = info

    [paths]
    provisioning = /etc/grafana/provisioning

    [server]
    root_url = https://grafana.gameforge.com
    enable_gzip = true

    [security]
    admin_user = admin
    cookie_secure = true
    strict_transport_security = true
    disable_gravatar = true

    [users]
    allow_sign_up = false
    auto_assign_org_role = Viewer

    [auth.anonymous]
    enabled = false

    [alerting]
    enabled = true
    execute_alerts = true

    [unified_alerting]
    enabled = true

    [feature_toggles]
    enable = ngalert

    [smtp]
    enabled = false
