# KIND Multi-Node Cluster Configuration for Production
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gameforge-production-ha

# Networking configuration
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
  disableDefaultCNI: false
  kubeProxyMode: "iptables"

# Cluster nodes configuration
nodes:
# Control plane node
- role: control-plane
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "tier=control-plane,environment=production"
        system-reserved: "cpu=200m,memory=500Mi"
        kube-reserved: "cpu=200m,memory=500Mi"
        eviction-hard: "memory.available<100Mi,nodefs.available<10%"
  - |
    kind: ClusterConfiguration
    apiServer:
      # Enable audit logging
      extraArgs:
        audit-log-maxage: "30"
        audit-log-maxbackup: "3"
        audit-log-maxsize: "100"
        audit-log-path: "/var/log/audit.log"
        audit-policy-file: "/etc/kubernetes/audit-policy.yaml"
        enable-admission-plugins: "NodeRestriction,PodSecurityPolicy"
        feature-gates: "PodSecurity=true"
      extraVolumes:
      - name: audit-policy
        hostPath: "/etc/kubernetes/audit-policy.yaml"
        mountPath: "/etc/kubernetes/audit-policy.yaml"
        readOnly: true
        pathType: File
  extraMounts:
  - hostPath: ./audit-policy.yaml
    containerPath: /etc/kubernetes/audit-policy.yaml
    readOnly: true
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP

# Worker nodes for high availability
- role: worker
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "tier=worker,environment=production,node-type=compute"
        system-reserved: "cpu=200m,memory=500Mi"
        kube-reserved: "cpu=200m,memory=500Mi"
        eviction-hard: "memory.available<100Mi,nodefs.available<10%"
        max-pods: "150"
  extraMounts:
  - hostPath: /var/lib/kubelet
    containerPath: /var/lib/kubelet
    propagation: Bidirectional

- role: worker
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "tier=worker,environment=production,node-type=compute"
        system-reserved: "cpu=200m,memory=500Mi"
        kube-reserved: "cpu=200m,memory=500Mi"
        eviction-hard: "memory.available<100Mi,nodefs.available<10%"
        max-pods: "150"
  extraMounts:
  - hostPath: /var/lib/kubelet
    containerPath: /var/lib/kubelet
    propagation: Bidirectional

- role: worker
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "tier=worker,environment=production,node-type=monitoring"
        system-reserved: "cpu=200m,memory=500Mi"
        kube-reserved: "cpu=200m,memory=500Mi"
        eviction-hard: "memory.available<100Mi,nodefs.available<10%"
        max-pods: "150"
  extraMounts:
  - hostPath: /var/lib/kubelet
    containerPath: /var/lib/kubelet
    propagation: Bidirectional

# Feature gates for modern Kubernetes features
featureGates:
  PodSecurity: true
  CSIStorageCapacity: true
  KubeletPodResources: true
