# Harbor Configuration
hostname: harbor.gameforge.com
http:
  port: 80
https:
  port: 443
  certificate: /data/cert/server.crt
  private_key: /data/cert/server.key

harbor_admin_password: ${HARBOR_ADMIN_PASSWORD}

database:
  password: ${HARBOR_DB_PASSWORD}
  max_idle_conns: 50
  max_open_conns: 1000

data_volume: /data

trivy:
  ignore_unfixed: false
  skip_update: false
  offline_scan: false
  security_check: true
  insecure: false
  github_token: ${GITHUB_TOKEN}

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 2.9.0

proxy:
  http_proxy: ""
  https_proxy: ""
  no_proxy: "127.0.0.1,localhost,.local,.internal"
  components:
    - core
    - jobservice
    - trivy

# Scanner integration
scanner:
  trivy:
    enabled: true
    url: http://trivy-server:4954
    token: ${TRIVY_TOKEN}

  # Additional scanners
  clair:
    enabled: true
    url: http://clair:6060

  # Custom vulnerability database
  vulnerability_database:
    type: embedded
    update_interval: 12h
