global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'gameforge-security'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'security-scanner'
    static_configs:
      - targets: ['security-scanner:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'harbor-registry'
    static_configs:
      - targets: ['harbor-registry:8080']
    metrics_path: '/api/v2.0/metrics'
    scrape_interval: 60s

  - job_name: 'clair-scanner'
    static_configs:
      - targets: ['clair-scanner:6061']
    metrics_path: '/metrics'
    scrape_interval: 60s

  - job_name: 'policy-engine'
    static_configs:
      - targets: ['security-policy-engine:8181']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'sbom-generator'
    static_configs:
      - targets: ['sbom-generator:8080']
    metrics_path: '/metrics'
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
