name: Secret Rotation

on:
  schedule:
    # Internal secrets - Daily at 1 AM UTC
    - cron: '0 1 * * *'
    # Application secrets - Every 45 days (manually triggered for now)
    # Database secrets - Every 90 days (manually triggered for now)
    
  workflow_dispatch:
    inputs:
      secret_type:
        description: 'Secret type to rotate'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - root
        - application
        - tls
        - internal
        - database
      force_rotation:
        description: 'Force rotation even if not due'
        required: false
        type: boolean
        default: false
      dry_run:
        description: 'Dry run mode'
        required: false
        type: boolean
        default: false

jobs:
  rotate-secrets:
    runs-on: windows-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup PowerShell
      shell: pwsh
      run: |
        Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"
        
    - name: Run Secret Rotation
      shell: pwsh
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        $params = @{
          Environment = "production"
          SecretType = "${{ github.event.inputs.secret_type || 'internal' }}"
        }
        
        if ("${{ github.event.inputs.force_rotation }}" -eq "true") {
          $params.ForceRotation = $true
        }
        
        if ("${{ github.event.inputs.dry_run }}" -eq "true") {
          $params.DryRun = $true
        }
        
        ./enterprise-secret-rotation.ps1 @params
        
    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rotation-logs
        path: logs/
        retention-days: 30
